# Generated by Django 2.0.1 on 2019-03-05 09:44

from django.db import migrations


def create_data(apps, schema_editor):
    Product = apps.get_model('main', 'Product')
    # This created a fake product when run in the migration
    Product(product_name='Product 001',
            product_type='Top',
            product_owner='tsdev',
            price=35,
            description='This is product number 1',
            thumbnail='main/images/image1.jpg'
            ).save()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
